### ISSUE TITLE
Log-in UX improvements

### ISSUE THREAD

**Issue by jayqui** [tricycle/eaforum#28]
I tried to upvote a comment.

I was then greeted by a modal window that asked me to login.  Two issues:
-  As a user I felt like I should be able to hit escape to exit this modal window, but this was not the case.
-  As a user I expected to be taken back to the post page after login (i.e., the post on which the comment I was trying to upvote was a comment).  Instead I was taken to a dedicated page for the comment itself.

I may get to offering a pull request with these tweaks, but I'm only presently a Ruby/Rails developer and not yet really familiar with Python or Django.

Thanks and best wishes,
Jay

**Comment by patbl** [comment]
Hey, Jay. I added the issues [here](https://github.com/tog22/eaforum/issues/) because we can't tag or close issues that belong to this repository. Thanks for the suggestions!

**Comment by patbl** [comment]
Both these issues have been fixed, so someone with sufficient privileges can close this.

**Comment by cattruscott** [comment]
Closing it then! :)
