### ISSUE TITLE
Confirmation email not working in Chrome on Yosemite.

### ISSUE THREAD

**Issue by RyanCarey** [tricycle/eaforum#3]
Hey folks, one user has let me know that the confirmation emails aren't working for them (they work fine for me though):

"the script for the confirmation e-mail seems not to work, I have tried thrice to receive one now.

Well on the homepage it tells me in order to be able to participate I have to verify my email address. I click on the link, it opens up a tab where I could enter a code or I can click to get a new email sent. I click the link in order to get an email. Nothing happens.

OSX Yosemite with Chrome.
I've checked my spam folder"

His email is konrad.seifert [at] t-online.de

Edit: this problem was resolved by using a gmail address. So as long as you guys think the emails are being handled in a sensible way, you can close this.

**Comment by tog22** [comment]
I'll try creating some accounts to test this out. Would someone else on
this list be able to check the server email logs to see if messages were
sent to Ryan's user (or any of mine which yield this error)?

**Comment by wezm** [comment]
I have confirmed that the server is sending email. The logs indicate that all emails sent to this user's address were delivered without error:

```
Apr 17 03:10:35 egg postfix/smtp[19929]: 4AC204191F: to=<xxx@t-online.de>, relay=mail.trikeapps.com:25, delay=0.66, delays=0.03/0.03/0.46/0.15, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as CAE77B953F)
Apr 17 03:10:35 egg postfix/qmgr[4700]: 4AC204191F: removed
```

**Comment by RyanCarey** [comment]
Ok, sounds like we can call it an issue with his email provider. He's
online using his gmail account, anyway. Cheers, folks.
